### ISSUE TITLE
401 Client Error: Unauthorized

### ISSUE THREAD

**Issue by bukosabino** [alpacahq/alpaca-backtrader-api#12]
Hi,

I sign up on https://app.alpaca.markets and I get the api_key and secret_key. Then, I try to run the `README` example, but I get this error:

```
401 Client Error: Unauthorized for url: https://api.polygon.io/v1/historic/agg/day/AAPL?from=2015-01-01T00%3A00%3A00&to=2019-06-20T11%3A42%3A17.626323&apiKey=<my_api_key>
```

What can I do?

Best,
Dario

**Comment by mercalli** [comment]
This was frustrating to me as it isn't obvious, but it is mentioned here https://docs.alpaca.markets/api-documentation/web-api/market-data/#polygon-integration
TL:DR - You need a live account to get data, paper accounts are only able to send orders and check account values. I assume it's because of the license alpaca has with polygon with respect to data access.

**Comment by neilsmurphy** [comment]
This was a bit frustrating for me as well. Alpaca allows for sign up and provides a "My Paper Trading API" with an Endpoint, Key ID, and Secret Key. This suggest that paper trading is available since a key is provided. 

However, as stated in this thread above, it appears that paper trading only supports sending orders and checking account values. If further appears that in order to paper trade with data or live trade one needs to be a US citizen, which is not mentioned until the next page. 

This situation cost me several hours trying to figure out from a techincal perspective why I couldn't connect with the api and get data. 

I would suggest the inclusion of some additional documentation underneath the "My Paper Trading API" to clarify what and who can paper trade, so that new users will understand if they can paper trade from the beginning.

**Comment by umitanuki** [comment]
Understood the frustration. We will clarify more. If you have any suggestion in the docs (https://alpaca.markets/docs) you can send PR too (https://github.com/alpacahq/user-docs)

**Comment by corescan** [comment]
I'm dealing with this same issue; I even have a live account and getting 401 when using this lib to connect with my key and secret. I had to set `paper: false` to successfully connect, which is a little terrifying for development.

So far I'm severely unimpressed with documentation in Alpaca.
