### ISSUE TITLE
Orders Limit Price and Stop Price not working

### ISSUE THREAD

**Issue by kr011** [alpacahq/alpaca-backtrader-api#50]
Placing a bracket order as follows should result in an order with a limit and a stop price:
```
self.buy_bracket(data=d, exectype=bt.Order.Market, stopprice=stop_price, limitprice=take_prof, 
 size=qty)
```
However, it looks like this order just ends up being a regular buy order with no limit/stop price. Also it looks like all 3 orders of the bracket are accepted, which is strange that we just end up with one regular buy order.

**Comment by shlomikushchi** [comment]
Hi, 
I added support for the bracket order.
it will be released to pypi in the next release.
you could install it directly from github right now like this:
`pip install git+https://github.com/alpacahq/alpaca-backtrader-api`

**Comment by kr011** [comment]
@shlomikushchi thanks. What version is this going to be in? I noticed 0.8.0 is out, but doesn't look like this fix is in it.

**Comment by kr011** [comment]
I just tested this with a install of master branch like you suggested, but still I don't see it working. This is how I place the order:

```
take_prof = d.close[0]*1.05
stop_price = d.close[0]*0.95

orders = self.buy_bracket(
    data=d, 
    exectype=bt.Order.Market,
    stopprice=stop_price,
    limitprice=take_prof,
    size=10
)
```
And here is what I see in Alpaca closed orders:
![image](https://user-images.githubusercontent.com/47929135/83431338-09306f80-a3ec-11ea-8bd9-96587881b8ae.png)

**Comment by shlomikushchi** [comment]
you are supposed to see the stop and take profit orders in the open orders, not the closed orders

**Comment by kr011** [comment]
Oh I see. Yeah that works thank you.

**Comment by arahmed24** [comment]
@shlomikushchi thank you for great posts. We are using Backtrader with Alpaca were able to submit a bracket order as you suggested. 

Is there a way to submit the stop price as the percent of to be executed price instead of a pre-calculated value? i.e. We want to submit a market order with stop loss of .1%. 

Thanks in advance!

**Comment by kr011** [comment]
@arahmed24 why don't you just calculate it like this "stopprice=self.data0.close[0]*0.999" (assuming you are going long)

**Comment by arahmed24** [comment]
@kr011 Thanks for your response. That's what we are currently doing, we calculate the stop price based on closed price and submit it with the order. Our preference is to submit a stop loss as a percent of the executed price, not calculated based on the current price or close price. Let's take an example.  Assume the close price 100 when we submit the but it gets filled at 100.99/9executed price), in this case, we want the stop loss to be 100.99*.999 instead of 100 *.999.  

Thanks

**Comment by kr011** [comment]
@arahmed24 understood. I think it's better for you to open a new issue, as this one was a request to implement bracket orders, which was completed and already closed.

**Comment by arahmed24** [comment]
@kr011 will do :) Thanks for your help.
