### ISSUE TITLE
Cache Feed Responses

### ISSUE THREAD

**Issue by mcrowson** [alpacahq/alpaca-backtrader-api#71]
I've been running a few different strategies and tweaking using the same data feed. Each time it makes a call out to the alpaca servers for the data. Would be nice if we could cache the request/responses locally for faster iterations and less load on your servers.

**Comment by shlomikushchi** [comment]
doing the api call doesn't take much time. the caching will not help improve the execution time

**Comment by mcrowson** [comment]
Understood, another benefit of caching would be to mitigate any 429 responses from the rate limiting.

**Comment by shlomikushchi** [comment]
it definitely has advantages. but currently I don't think it's worth it
caching is complicated. what happens when you change dates? how to merge cached and uncached data? how to clear the cache?
everything is doable of course. but the benefits are not enough I think
I will keep it mind if I think in the near future it's worth the time required I'll do it

**Comment by mcrowson** [comment]
For those that come here later, I found this library did the caching for me pretty seamlessly. https://pypi.org/project/requests-cache/ 

Another caching library option would be https://github.com/ionrock/cachecontrol but it requires wrapping the session instance which gets created at alpaca python API REST instantiation (outside the scope of this repo).
